---
title: "PA1_template"
author: "Brayan D"
date: "11/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)

unzip("activity.zip")
data1 <- read.csv("activity.csv", colClasses=c("numeric", "Date", "numeric"))


# Calculate the total number of steps taken per day
data <- data1[!(is.na(data1$steps)), ]

StepsbyDay <- aggregate(steps ~ date, data, sum)
StepsbyDay

# If you do not understand the difference between a histogram and a barplot, 
# research the difference between them. Make a histogram of the total number of steps taken each day

hist(StepsbyDay$steps, breaks=25, xlab="Number of Steps Taken", 
     main="Total Number of Steps Taken per Day", col = "blue")

# Calculate and report the mean and median of the total number of steps taken per day
summarise(StepsbyDay, mean=mean(StepsbyDay$steps),
                               median=median(StepsbyDay$steps))


# Make a time series plot (type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
StepsInterval <- aggregate(steps ~ interval, data, mean)
StepsInterval


plot(StepsInterval$interval, StepsInterval$steps, type="l",
     main="Time Series Plot of Average Steps Taken",
     ylab="Number of Steps", xlab="Intervals",
     col="blue")


#Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
  
StepsInterval[grep(max(StepsInterval$steps), StepsInterval$steps), ]


# Calculate and report the total number of missing values in the dataset 

cbind(steps=sum(is.na(data1$steps)), 
           interval=sum(is.na(data1$interval)), 
           date=sum(is.na(data1$date)))


# Devise a strategy for filling in all of the missing values in the dataset

missing<-is.na(data1[,1])

prom<-mean(data1$steps, na.rm = TRUE)

imputed<-data1
imputed[missing,1]<-prom
head(imputed)

cbind(steps=sum(is.na(imputed$steps)), 
      interval=sum(is.na(imputed$interval)), 
      date=sum(is.na(imputed$date)))

# Create a new dataset that is equal to the original dataset but with the missing data filled in.

imputedSteps <- aggregate(steps ~ date, imputed, sum)
head(imputedSteps)

# Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day

hist(imputedSteps$steps, breaks=20, xlab="Number of Steps Taken", 
     main="Histogram of Total Number of Steps Taken per Day imputed",
     col="blue")


imputedStepsSummary <- summarise(imputedSteps, 
                                 meanOfSteps=mean(imputedSteps$steps), 
                                 medianOfSteps=median(imputedSteps$steps))  
imputedStepsSummary




# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” 

days <- imputed
days$days <- weekdays(days$date)
days$weekday <- as.character(rep(0, times=17568))
for(x in 1:17568) {
  if(days[x, 4] %in% c("Saturday", "Sunday")) {
    days[x, 5] <- "weekend"
  } else {
    days[x, 5] <- "weekday"
  }
}
days$weekday <- factor(days$weekday)
head(days)


weekday <- days[days$weekday=="weekday", ]
weekend <- days[days$weekday=="weekend", ]

weekdayMean <- aggregate(steps ~ interval, weekday, mean)
weekendMean <- aggregate(steps ~ interval, weekend, mean)

# Make a panel plot containing a time series plot

par(mfrow=c(1,2))

plot(weekdayMean$interval, weekdayMean$steps, type="l",
     main="Time Series Plot of Average Steps Taken per Interval (Weekdays)",
     xlab="Intervals", ylab="Number of Steps",
     col="blue", ylim=c(0, 230))

plot(weekendMean$interval, weekendMean$steps, type="l",
     main="Time Series Plot of Average Steps Taken per Interval (Weekends)",
     xlab="Intervals", ylab="Number of Steps",
     col="blue", ylim=c(0, 230))
```

